// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Family struct {
	ID      string    `json:"id"`
	Name    *string   `json:"Name"`
	Country *string   `json:"Country"`
	Members []*Member `json:"Members"`
}

type Member struct {
	ID     string  `json:"id"`
	Type   *string `json:"Type"`
	Person *Person `json:"Person"`
}

type Person struct {
	ID          string    `json:"id"`
	FirstName   string    `json:"FirstName"`
	LastName    string    `json:"LastName"`
	DateOfBirth string    `json:"DateOfBirth"`
	Country     *string   `json:"Country"`
	Spouse      *Person   `json:"Spouse"`
	Father      *Person   `json:"Father"`
	Mother      *Person   `json:"Mother"`
	Children    []*Person `json:"Children"`
}

type Work struct {
	ID       string    `json:"id"`
	Name     *string   `json:"Name"`
	Country  *string   `json:"Country"`
	Industry *string   `json:"Industry"`
	Ceo      *Person   `json:"CEO"`
	Employee []*Person `json:"Employee"`
}
